### ISSUE TITLE
Create "logging-lite" ElasticSearch deployment

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/chart-elasticsearch#3]
_From @leahnp on August 1, 2017 23:17_

Duplicate this repo as much as possible for maintainability.
Use a single statefulset to spinup a light weight single node data/master elasticsearch cluster
Use elastic curator to delete logs after 2 weeks.

_Copied from original issue: samsung-cnct/elasticsearch-kubernetes#10_

**Comment by guineveresaenger** [comment]
Questions:
1. Since the elasticsearch-kubernetes repo is deprecated as of today, should we base this on the chart-elasticsearch repo?
2. Following this logic, should this deployment come in the form of a helm chart?
3. Would the memory resources remain the same as for a full-size logging application?
4. I'm not entirely sure I follow what is "logging-lite" compared to chart-elasticsearch. Can someone elaborate?

**Comment by leahnp** [comment]
1. All work should be based off: chart-elasticsearch repo. This work will involve a bit of research to establish:

- what our team views as a minimum elasticsearch deployment
- how to define and deploy logging lite es vs central es - I feel like it could be handled via this ticket: https://github.com/samsung-cnct/k2-charts/issues/120 in the form of fewer and smaller master/data nodes and defined in the helm chart's "value" file.

3. The point of a lighter es deployment would be to use less resources.
4. The 'logging-lite' chart will include fluent-bit and elasticsearch in the same chart. When you install the chart both will spin up together and be able to communicate. "chart-elasticsearch" is ONLY elasticsearch.

With the landscape of our currently work I think the deliverables of this ticket should inform https://github.com/samsung-cnct/k2-charts/issues/120 we should research community standards and establish:

- minimum master and data node number and size
- minimum time to hold data in cluster

You can document your findings as a comment here: https://github.com/samsung-cnct/k2-charts/issues/120

**Comment by guineveresaenger** [comment]
This issue is being closed in favor of using https://github.com/samsung-cnct/chart-elasticsearch as a dependency for "logging-lite" chart.
We decided we care about fault tolerance and resilience in terms of capacity enough that creating another chart repo with a potentially lighter elasticsearch deployment is not a compelling advantage. While it is desirable to use fewer resources, reliability and ease of repository maintenance is currently more important.
